### ISSUE TITLE
Cant implement "CTSoftPhoneDelegate", and ".sharedInstance(with: self)"

### ISSUE THREAD

**Issue by HZ4ever228** [CleverTap/CTSoftPhone#1]
When i try to add sharedInstanse - its said: "Type 'CTSoftPhone' has no member 'sharedInstance'".
The same sink - with "CTSoftPhoneDelegate": - Cannot find type 'CTSoftPhoneDelegate' in scope, 

But readme file - said than this to options should be here. 

P.S. one day, when i add a new method in ours work Package, i forgot to make it "public" , and i saw probably same errors.
P.P.S. Thank you for yours work!

**Comment by pwilkniss** [comment]
@HZ4ever228 will publish an updated framework today - you caught me in between updating the readme and doing that sorry!

**Comment by pwilkniss** [comment]
@HZ4ever228  https://github.com/CleverTap/CTSoftPhone/releases/tag/0.0.4-alpha

**Comment by HZ4ever228** [comment]
Thank you!
