### ISSUE TITLE
I have a problem with hardcoded :7503

### ISSUE THREAD

**Issue by HZ4ever228** [CleverTap/CTSoftPhone#2]
When i try to connect to Sip server - libary allways give an :7503 in the end. 
I am alreaddy clone your project to change hardcoded values :7503 in CTSoftPhone.m file, but when i build the project again - i see:
" tcptp:7503  SIP TCP listener ready for incoming connections at 192.168.0.20:7503
 pjsua_core.c  .Invalid route URI: sip:"my sip host":7503;transport=tcp
   tcptp:7503  .SIP TCP transport destroyed
   "
   As you can see - there are :7503 everywhere, and there is no chanse to change it. Also is no possible to find "pjsua_core.c" file to change values there.

**Comment by pwilkniss** [comment]
@HZ4ever228 right now the port (7503) and transport (TCP) are hard coded - i can add a configuration option - will try to do that in the next couple of days

**Comment by HZ4ever228** [comment]
@pwilkniss, Super, I will wait for it. Thanks

**Comment by pwilkniss** [comment]
@HZ4ever228 please try the 0.0.5-alpha release

you will need to update your initialization to something like this:
// create config with port and transport type
let pjsipConfig = CTSoftPhoneConfig.init(port: 7503, transport: .TCP)

// init sharedInstance with your delegate and config
pjsipInstance = CTSoftPhone.sharedInstance(with: self, config: pjsipConfig)

Also please do note the caveats i have added to the latest README

**Comment by HZ4ever228** [comment]
@pwilkniss , perfect. Thank you
